from enum import Enum

class DevPhase(Enum):
    UNDERSTAND = "1_UNDERSTAND"
    ARCHITECTURE = "2_ARCHITECTURE"
    STRUCTURE_CODE = "3_STRUCTURE_CODE"
    STRUCTURE_TESTS = "4_STRUCTURE_TESTS"
    FLESH_OUT_CODE = "5_FLESH_OUT_CODE"
    FLESH_OUT_TESTS = "6_FLESH_OUT_TESTS"
    DEPLOY = "7_DEPLOY"
    IMPROVE = "8_IMPROVE"

class InferenceStep(Enum):
    IDEATE = "1_IDEATE"
    CRITIQUE = "2_CRITIQUE"
    RESOLVE = "3_RESOLVE"
