from enum import Enum

class DevPhase(Enum):
    UNDERSTAND = "1_UNDERSTAND"
    ARCHITECTURE = "2_ARCHITECTURE"
    STRUCTURE_CODE = "3_STRUCTURE_CODE"
    STRUCTURE_TESTS = "4_STRUCTURE_TESTS"
    WRITE_CODE = "5_WRITE_CODE"
    IMPROVE_CODE = "6_IMPROVE_CODE"
    WRITE_TESTS = "7_WRITE_TESTS"
    IMPROVE_TESTS = "8_IMPROVE_TESTS"
    DEPLOY = "9_DEPLOY"
    IMPROVE = "10_IMPROVE"

class InferenceStep(Enum):
    SIMPLE = ""
    IDEATE = "1_IDEATE"
    CRITIQUE = "2_CRITIQUE"
    RESOLVE = "3_RESOLVE"
